Fix username/password authentication in HttpUtils.
We were getting the following error when accessing a URL that requires a username and password:
java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>

Tracked it down to a dependency: net.java.dev.jets3t was including commons-codec 1.3 and
commons-codec 1.2 (via commons-httpclient 3.1).

Apache commons-httpclient includes commons-codec 1.9.